alioth: Define TARGET_GRALLOC_HANDLE_HAS_RESERVED_SIZE
- Updated display stack requires to use GRALLOC_HANDLE_HAS_RESERVED_SIZE

[Reference]:
- VoidUI-Tiramisu/vendor_aosp@6e92cbb6b1e23e5cd3db4517fc8b39316a7769cb
- VoidUI-Tiramisu/vendor_qcom_opensource_commonsys-intf_display@063620ac8f2f1e71315f22cbb289b856c4473787
- VoidUI-Tiramisu/vendor_qcom_opensource_commonsys-intf_display@7d4de03ac1428bad36ccde0d950540dae731988e

[Fixing following errors]:
hardware/qcom-caf/sm8250/display/gralloc/gr_buf_mgr.cpp:107:43: error: no member named 'reserved_size' in 'private_handle_t'
  uint64_t reserved_region_size = handle->reserved_size;
                                  ~~~~~~  ^
hardware/qcom-caf/sm8250/display/gralloc/gr_buf_mgr.cpp:125:45: error: no member named 'reserved_size' in 'private_handle_t'
    uint64_t reserved_region_size = handle->reserved_size;
                                    ~~~~~~  ^
hardware/qcom-caf/sm8250/display/gralloc/gr_buf_mgr.cpp:752:41: error: no member named 'reserved_size' in 'private_handle_t'
  auto meta_size = getMetaDataSize(hnd->reserved_size);
                                   ~~~  ^
hardware/qcom-caf/sm8250/display/gralloc/gr_buf_mgr.cpp:1087:8: error: no member named 'reserved_size' in 'private_handle_t'
  hnd->reserved_size = descriptor.GetReservedSize();
  ~~~  ^
4 errors generated.

Change-Id: I160fe9b58eec874f70e6e637fc8f23d47c02574f